### ISSUE TITLE
Crash when checking mini miner on bauxrite ore from Tech Reborn [1.18.2 Fabric]

### ISSUE THREAD

**Issue by valkyrienyanko** [Skylortrexler/MiniMiner#2]
Crash log from NotEnoughCrashes: https://crashy.net/gMOOwjcqCYkyRJNPExaG

Full crash log
```
---- Minecraft Crash Report ----
// My bad.

Time: 2022-07-07, 5:37 p.m.
Description: Rendering screen

java.lang.ArithmeticException: / by zero
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.1)
	at website.skylorbeck.miniminer.screen.MiniMinerScreenHandler.getFuelProgress(MiniMinerScreenHandler.java:92)
	at website.skylorbeck.miniminer.screen.MiniMinerHandledScreen.drawBackground(MiniMinerHandledScreen.java:39)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen:100)
	at website.skylorbeck.miniminer.screen.MiniMinerHandledScreen.render(MiniMinerHandledScreen.java:25)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:877)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at website.skylorbeck.miniminer.screen.MiniMinerScreenHandler.getFuelProgress(MiniMinerScreenHandler.java:92)
	at website.skylorbeck.miniminer.screen.MiniMinerHandledScreen.method_2389(MiniMinerHandledScreen.java:39)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at website.skylorbeck.miniminer.screen.MiniMinerHandledScreen.method_25394(MiniMinerHandledScreen.java:25)

-- Screen render details --
Details:
	Screen name: website.skylorbeck.miniminer.screen.MiniMinerHandledScreen
	Mouse location: Scaled: (240, 135). Absolute: (960.000000, 540.000000)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 2 total; [class_746['valkyrienyanko'/697729, l='ClientLevel', x=-561.84, y=90.00, z=412.96], class_745['Psychopomp3'/347, l='ClientLevel', x=-602.70, y=110.00, z=368.51]]
	Chunk stats: 16384, 903
	Level dimension: minecraft:overworld
	Level spawn location: World: (80,75,-16), Section: (at 0,11,0 in 5,4,-1; chunk contains blocks 80,-64,-16 to 95,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 3025089 game time, 1399214 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1270085208 bytes (1211 MiB) / 5603590144 bytes (5344 MiB) up to 9663676416 bytes (9216 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.15021.11005
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23288.22
	Virtual memory used (MB): 20018.50
	Swap memory total (MB): 6973.71
	Swap memory used (MB): 421.75
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancednetherite: Advanced Netherite 1.5.1-1.18.2
		advdebug: Advancements Debug 2.3.0
		ambientenvironment: Ambient Environment 7.0+19
		ambientsounds: Ambiend Sounds (Fabric) 5.0.16
		appleskin: AppleSkin 2.4.0+mc1.18.2
		aqupdgrizzly: Grizzly Bear mob 1.18-1.3
		architectury: Architectury 4.5.76
		attributefix: AttributeFix 14.0.2
		automated_crafting: Automated Crafting 1.4.4
			libgui: LibGui 5.3.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		badwithernocookiereloaded: Bad Wither No Cookie! Reloaded 3.10.18 (Fabric 1.18.2)
		balm-fabric: Balm 3.1.0+0
		bcc: BetterCompatibilityChecker fabric-1.0.5
		bclib: BCLib 1.4.7
		beo: Basic End Ores 1.18.2-2.1.0-Fabric
		betteradvancements: Better Advancements 0.2.1.132
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		betterdeserttemples: YUNG's Better Desert Temples 1.18.2-Fabric-1.1.0
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterend: Better End 1.1.1
		betterfpsdist: Better FPS distance Mod 1.18-1.8
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.2
		betternether: Better Nether 6.1.2
		betterpingdisplay: Better Ping Display 1.1.1
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		betterthirdperson: Better Third Person 1.8.1
		betterwitchhuts: YUNG's Better Witch Huts 1.18.2-Fabric-1.0.1
		blur: Blur (Fabric) 2.4.1
			midnightlib: MidnightLib 0.3.1
		bno: Basic Nether Ores 1.18.2-7.2.0-Fabric
		bookshelf: Bookshelf 13.2.21
		bowinfinityfix: Bow Infinity Fix rv11
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chat_heads: Chat Heads 0.6.0
		chunky: Chunky 1.2.164
		cleancut: CleanCut 1.18.2-5.0-fabric
		clickadv: Clickable Advancements Mod 2.6
		climbladdersfast: ClimbLaddersFast 2.2.2-1.18
		cloth-api: Cloth API 3.2.64
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+10
		connectivity: Connectivity Mod 1.18.2-3.3
		controlling: Controlling For Fabric 9.0+21
		crafttweaker: CraftTweaker 9.1.162
			org_javassist_javassist: javassist 3.29.0-GA
			org_reflections_reflections: reflections 0.10.2
		create: Create mc1.18.2_v0.4.1+637
			com_electronwill_night-config_core: core 3.6.3
			com_electronwill_night-config_toml: toml 3.6.3
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 1.18-0.7.0.26
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			noindium: No Indium? 1.0.1+1.18.2
			porting_lib: Porting Lib 1.1.317-beta+1.18.2-dev.7ad1f24
				com_github_llamalad7_mixinextras: MixinExtras 0.0.10
				mm: Manningham Mills 2.3
				serialization_hooks: Serialization Hooks 0.2.0+1.18.f5d4aa6
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			registrate-fabric: Registrate for Fabric MC1.18.2-1.0.3
		createaddition: Create Crafts & Additions ${version}
			team_reborn_energy: Energy 2.2.0
		createchunkloading: Create Chunkloading 1.1.0
		createplus: CreatePlus 1.0
		creativecore: CreativeCore (Fabric) 2.6.12
		creeperoverhaul: Creeper Overhaul 1.3.1
		croptopia: Croptopia 2.0.5
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		cullleaves: Cull Leaves 2.3.2
		cyti: Can You Trash It? 1.0.5
		dadobugbedrockores: Dadobug1111's Bedrock Ores 1.3.6
		dawn: Dawn API 3.3.2
		denseores: Dense Ores: Refabricated 1.2.2+1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
			omega-config-gui: Omega Config GUI 1.2.3-1.18.1
				cloth-config-lite: cloth-config-lite 2.0.6
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		dragonloot: DragonLoot 1.1.0
		dual_riders: Dual Riders 1.1.1
		dynview: Dynamic View Mod 1.18.2-2.2
		effective: Effective 1.2.1
		enchdesc: EnchantmentDescriptions 10.0.4
		entityculling: EntityCulling-Fabric 1.5.1
		expandedstorage: Expanded Storage 7.3.12
		experiencebugfix: Experience Bug Fix 18
		extraalchemy: Extra Alchemy 1.8.1
		extractinatortweaks: Extractinator Tweaks 1.0-SNAPSHOT-3
		fabric: Fabric API 0.57.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.2+d005b03a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabricloader: Fabric Loader 0.14.8
		fallingleaves: Falling Leaves 1.11.1+1.18.2
		fallingtree: FallingTree 3.5.3
		farsight: Farsight Mod 1.18-1.9
		faux-custom-entity-data: Faux-Custom-Entity-Data 1.0.4
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		flesh2leather: Flesh2Leather 1.0.3+1.18.2
		flytre_lib: FlytreLib 1.8.1
		forgeconfigapiport: Forge Config API Port 3.2.0
		fpsreducer: FPS Reducer 1.18.2-2.0
		ftblibrary: FTB Library 1802.3.6-build.123
		ftbultimine: FTB Ultimine 1802.3.3-build.55
		gearreborn: Gear Reborn 1.18.2-0.1.14
			autoconfig1u: Auto Config v1 Updated 3.4.0
		geckolib3: Geckolib 3.0.50
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		go-fish: Go Fish 1.5.0-1.18.2
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.14
		iceberg: Iceberg 1.0.38
		identity: Identity 2.3.0-1.18.2
		iknowwhatimdoing: I Know What I'm Doing 4.1.0
		ikwid_fabric: I know what I'm doing! [FABRIC] 1.1+1.18.x
		improved-stations: Improved Stations 2.1.0
		indium: Indium 1.0.6+mc1.18.2
		ingredient-extension-api: Ingredient Extension API 2.0.6
		initialinventory: Initial Inventory 6.0.8
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		jade: Jade 5.99.5
		jamlib: JamLib 0.0.5
		java: OpenJDK 64-Bit Server VM 17
		jumpoverfences: JumpOverFences 1.16-0.0.3
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		lanserverproperties: Lan Server Properties 1.8
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.5
		libraryferret: Library Ferret 2.0.0
		limitmobspawn: LimitMobSpawn 18.2-fabric
		lithium: Lithium 0.7.10
		maxhealthfix: MaxHealthFix 5.0.1
		memoryleakfix: memory Leak Fix 1.18.2-0.3.5
		memorysettings: Memorysettings Mod 1.18.2-2.2
		minecraft: Minecraft 1.18.2
		minieffects: Mini Effects 4.1.0
		miniminer: Miniminer 1.0.1
		mining_dims: Mining Dimensions 1.3.8
			customportalapi: Custom Portal Api 0.0.1-beta50-1.18
			pugh_lib: Pugh Lib 1.3.0
		mob_catcher: Mob Catcher 1.1.27
		modmenu: Mod Menu 3.2.3
		morevillagers: More Villagers 3.3.2
		mousetweaks: Mouse Tweaks 2.22
		netherportalfix: NetherPortalFix 9.0.0
		ngv: Nether Gold Veins 1.2.0
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.3.0
		no_angled_brackets: No Angled Brackets 1.0.0
		no_fog: No Fog 1.2.2+1.16.5-1.18.2
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		pickupnotifier: Pick Up Notifier 3.2.0
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		polymorph: Polymorph 0.0.21-1.18.2
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
		puzzleslib: Puzzles Lib 3.3.5
		quarryplus: QuarryPlus 18.4.573
		quickhomes: QuickHomes 1.18.2-1.3.0
		rare-ice: Rare Ice 0.4.1
		reborncore: Reborn Core 5.2.0
		reroll: Reroll 1.5.0-1.18.2
		rightclickharvest: Right Click Harvest 2.1.1
		roughlyenoughitems: Roughly Enough Items 8.3.501
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		scannable: Scannable 1.7.7
		seamless_loading_screen: Seamless Loading Screen 1.4.0+1.18.2
		seedfix: Seed Fix 1.0.1
		simple_backpack: SimpleBackpack 1.2.37
		skylorlib: SkyLib 1.3.35
		smoothboot: Smooth Boot 1.18.2-1.7.0
		smoothchunk: Smooth chunk save Mod 1.18.2-1.9
		smootherbedrock: Smoother Bedrock 1.0.4
		soaringstructures2: Soaring Structures 2 1.18.2 - 2.3.1
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.6
		spark: spark 1.9.11
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		starlight: Starlight 1.0.2+fabric.89b8d9f
		stoneholm: Stoneholm 1.4.3
		t_and_t: Towns and Towers - Structure Add-on 1.6
		techreborn: Tech Reborn 5.2.0
		terrarianslimes: Terrarian Slimes 1.2.1-BETA+1.18
		the_aether: Paradise Lost 1.6.9+1.18.2
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
			gud_recipe_confidence: Recipe Confidence 1.0.2
			incubus_core: Incubus Core 1.6.6+1.18.2
			moretags: More Tags 3.0.4
			satin: Satin 1.7.2
		the_extractinator: The Extractinator 1.0.8
		tipthescales: Tip The Scales 5.0.6
		totemmod: Wither Totems Mod 0.3.5-1.18.2-pre2
		totw_additions: Towers of the Wild: Additions 1.2.1
		trinkets: Trinkets 3.3.1
		universal_ores: Universal Ores 1.3.0
		vanillatweaks: VanillaTweaks 1.5.58
		visuality: Visuality 0.4.2
			goosik-config: goosik-config 0.2.0
			tlcosmetica: Cosmetica 0.4.0
		waystones: Waystones 2.5.4
		wolveswitharmor: Wolves With Armor 1.7.1-1.18.2
			maybe-data: Maybe data 1.2.1-1.18.2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		woodarmor: Wooden Armors (+ Stone Armor) fabric-1.18.2-v1.0.1
		woodarmorhorse: Wooden Horse Armors fabric-1.18.2-v1.0.1
		woodenhoppers: Wooden Hoppers 1.2.0
		worldedit: WorldEdit 7.2.10+1742f98
		xaerominimap: Xaero's Minimap 22.10.0
		xaeroworldmap: Xaero's World Map 1.24.0
		xp_storage: XP Storage 1.4.3+1.18
		yigd: You're in Grave Danger 1.3.7
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.14.8-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series GL version 3.2.14800 Core Profile Forward-Compatible Context 22.5.1 30.0.15021.11005, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Miniminer (miniminer), Fabric Loader (fabricloader)
```

**Comment by skylorbeck** [comment]
Before I go any further, please ensure that you are using the version for 1.18.2 and not 1.19. NotEnoughCrashes appears to be for 1.19.1 but your MC version is 1.18.2. Please verify that this crash happens with the 1.18.2 version of MM. Both versions are 1.0.1, so it can be missed.

**Comment by valkyrienyanko** [comment]
![image](https://user-images.githubusercontent.com/6277739/177898189-3760f786-d6b2-458e-b2d9-0f5a9532f096.png)

**Comment by valkyrienyanko** [comment]
![image](https://user-images.githubusercontent.com/6277739/177898239-1949c731-bf27-4f80-ae10-11f1a591d458.png)

**Comment by valkyrienyanko** [comment]
![image](https://user-images.githubusercontent.com/6277739/177898624-f5c5f0c5-d35e-4117-be04-81989ad1a75c.png)

**Comment by skylorbeck** [comment]
Sorry, I was afraid that you'd interpret my request like that. I meant make sure you download the 1.18.2 version of MiniMiner 1.0.1. Thank you for posting those though, most people fight for some reason like I'm not also trying to figure it out haha.

**Comment by valkyrienyanko** [comment]
![image](https://user-images.githubusercontent.com/6277739/177906593-90a7708e-f143-40e5-8054-9ad24c020859.png)

**Comment by valkyrienyanko** [comment]
![image](https://user-images.githubusercontent.com/6277739/177906637-812c93c9-42c7-4e17-af5e-235e674eab72.png)

**Comment by skylorbeck** [comment]
Excellent thank you. I'll see what I can do to replicate it and hopefully fix it. Looks like it was caused by the fuel amount somehow being zero and not getting handled safely in a division. Thought I fixed that.
